name: myresume
description: flutter web.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.11
  url_launcher: ^6.0.18
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - myFile/image/


  fonts:
    - family: jhenghei
      fonts:
        - asset: myFile/font/jhenghei.ttf
    - family: iranSans
      fonts:
        - asset: myFile/font/IRANSansXFaNum-Medium.ttf
        
    - family: ResumeIcon
      fonts:
        - asset: myFile/font/ResumeIcon.ttf
      
    